### PR TITLE
clear expressions before updating values

### PR DESCRIPTION
**Pull request by Jsevenh**
I noticed that when a value is manually updated using an expression in FreeCAD, modifying the value programmatically in a script doesn't always reflect after a recompute. To address this, I've added logic to clear any existing expressions before attempting to update the value. Please note that I am still an amateur in FreeCAD development, so any feedback or suggestions for improvement are welcome

### CODE REVIEW

**Comment by drfenixion** [comment]
Hello, thank you for contribution. How i can test this? Could you prepare test case? 
I mean where and what i should type and what result expected with and without that fix.

**Comment by Jsevenh** [comment]
Manually edit a link property value, such as mass or inertia,  using an expression. Run the "Calculate Inertia" command and check if the value you modified has changed. To test, I suggest using an unrealistically large value. Afterward, clear the expression and re-run the command again  and  check if  the property value has changed

**Comment by drfenixion** [comment]
Hello, I remember about this PR but busy with big feature pack. I will process it after.

**Comment by drfenixion** [comment]
Thank you. Merged.

**Pull request merged**
